### ISSUE TITLE
Bug: Failed prop type IconButton 

### ISSUE THREAD

**Issue by MartinMarwad** [UMLCloudComputing/UniPath.io#121]
```
Warning: Failed prop type: MUI: You are providing an onClick event listener to a child of a button element.
Prefer applying it to the IconButton directly.
This guarantees that the whole <button> will be responsive to click events.
    at IconButton (webpack-internal:///(ssr)/./node_modules/@mui/material/IconButton/IconButton.js:127:85)
    at AppBarComponent (webpack-internal:///(ssr)/./src/components/AppBar/AppBar.js:69:32)
    at div
    at eval (webpack-internal:///(ssr)/./node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js:61:74)
    at Box (webpack-internal:///(ssr)/./node_modules/@mui/system/esm/createBox.js:34:76)
    at Layout (webpack-internal:///(ssr)/./src/app/(home)/layout.js:38:23)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:239:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:313:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:151:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:226:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:322:11)
    at Lazy
    at div
    at eval (webpack-internal:///(ssr)/./node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js:61:74)
    at Box (webpack-internal:///(ssr)/./node_modules/@mui/system/esm/createBox.js:34:76)
    at div
    at ViewPrimitive (webpack-internal:///(ssr)/./node_modules/@aws-amplify/ui-react/dist/esm/primitives/View/View.mjs:11:26)
    at AuthenticatorProvider (webpack-internal:///(ssr)/./node_modules/@aws-amplify/ui-react-core/dist/esm/Authenticator/context/AuthenticatorProvider.mjs:19:34)
    at ThemeProvider (webpack-internal:///(ssr)/./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:45:13)
    at ThemeProvider (webpack-internal:///(ssr)/./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:58:13)
    at ThemeProvider (webpack-internal:///(ssr)/./node_modules/@mui/material/styles/ThemeProvider.js:26:18)
    at MainApp (webpack-internal:///(ssr)/./src/app/layout.js:35:20)
    at ThemeContextProvider (webpack-internal:///(ssr)/./src/contexts/ThemeContext.js:14:33)
    at AppRouterCacheProvider (webpack-internal:///(ssr)/./node_modules/@mui/material-nextjs/v13-appRouter/appRouterV13.js:26:13)
    at body
    at html
    at RootLayout (webpack-internal:///(ssr)/./src/app/layout.js:73:23)
    at Lazy
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:296:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:155:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:99:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:421:13)
    at Lazy
    at Lazy
    at /home/martin/UMLCloudComputing/UniPath.io/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:381577
    at /home/martin/UMLCloudComputing/UniPath.io/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:381577
    at ServerInsertedHTMLProvider (/home/martin/UMLCloudComputing/UniPath.io/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:17605)
```

**Comment by nbottari9** [comment]
![Image](https://github.com/UMLCloudComputing/UniPath.io/assets/81245965/008d1778-0d4b-430f-8134-4968d5c7098b)

**Comment by nbottari9** [comment]
Probably coming from this
